### ISSUE TITLE
Chicago: Hardcore Go Workshop, Date & Location TBD

### ISSUE THREAD

**Issue by corylanou** [gobridge/workshops#10]
Organizer: @corylanou
Venue: TBD
Date: November-ish, TBD
Curriculum: Hardcore Go

Details and RSVP: TBD
- [ ] Confirm venue and date
- [ ]  Find curriculum, confirm license and what we can do with it
- [ ]  Sponsor for food breaks / drinks
- [ ]  Market it: write announcement
- [ ]  Market it: list of channels (ChicaGoLang, Chicago Hardcore Golang,  ... ?)
- [ ]  Maybe enroll help, TAs

**Comment by carlisia** [comment]
Closing this for now. We'll reopen it when we are ready to move forward.

**Comment by corylanou** [comment]
Sounds good.  I'm in Chicago in January and I'll talk to my contacts then. I mostly need a venue.  Once I have that figured out, the rest should fall into place pretty quickly.

**Comment by carlisia** [comment]
Perfect @corylanou! Maybe we can aim for a February workshop in Chicago!
