### ISSUE TITLE
Portland, OR : Date TBD : Go Workshop : Location TBD

### ISSUE THREAD

**Issue by freeformz** [gobridge/workshops#11]
Organizer: @freeformz, others welcome
Venue: TBD
Date: January-ish, TBD
Curriculum: TBD

Details & RSVP: TBD
- [ ] Enroll Help ([inspiration](https://github.com/railsbridge/docs/wiki/Cookbook))
- [ ] Confirm vendur and date
- [ ] Find curriculum, confirm license and what we can do with it
- [ ] Sponsor for food breaks / drinks
- [ ] Market it: Write announcement
- [ ] Market it: Mailing List
- [ ] Merket it: Twitter / PDX Go / [BridgeTroll[(https://www.bridgetroll.org/) / Etc

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Two to four weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:  
- [ ] Retro

:tulip:

**Comment by carlisia** [comment]
Closing this for now. We'll reopen it when we are ready to move forward.
