### ISSUE TITLE
Portland, OR: Dec 5th & 6th 2015 : Hardcore Go Workshop - Venue: Intel

### ISSUE THREAD

**Issue by ardan-bkennedy** [gobridge/workshops#13]
This is being organized by a group in the area. I have listed this here just to have a record.

**Comment by carlisia** [comment]
Update: Waiting for the registration page so we can start announcing.

**Comment by carlisia** [comment]
http://www.meetup.com/gobridge/events/226705136/

**Comment by freeformz** [comment]
@carlisia is there a BridgeTroll thing for this?

**Comment by carlisia** [comment]
Hey @freeformz not for this one; we are using meetup. Going forward we will be using BridgeTroll.

**Comment by freeformz** [comment]
I'm TA'ing.
@Ropes is also interested in helping out.

**Comment by Ropes** [comment]
I'm happy to help where capable. However, I'm not highly experienced with Go. So if it's alright I'll step back and listen if the workshop surpasses my know how.
