### ISSUE TITLE
NYC : Oct 3rd & 4th : Hardcore Go Workshop - Venue: Digital Ocean (@womenwhogo_nyc)

### ISSUE THREAD

**Issue by ardan-bkennedy** [gobridge/workshops#2]
Organizer: @womenwhogo_nyc
Venue: Digital Ocean
Date: Oct 3/4
Curriculum: Hardcore Go
- [x] Need to locate a space for the event
- [x] Need sponsor for travel and refreshments

**Comment by peggyl** [comment]
@ardan-bkennedy The issue has SF in the name but the NYC label, and Google has offices in both cities. ☺

**Comment by ardan-bkennedy** [comment]
@peggl thanks for catching that. I need to fix the title to say NYC.

**Comment by Lyoness** [comment]
@ardan-bkennedy Women Who Go NYC will take logistical ownership for this event.
