### ISSUE TITLE
San Francisco - Date: February 2016 - Course: Building Web Apps With Go - Venue: Sagan Systems

### ISSUE THREAD

**Issue by allyvigil** [gobridge/workshops#20]
Organizers: @Randommood, @freeformz
Venue: Sagan Systems, 611 Mission St. San Francisco
Date: February 2016
### Logistic items
- [x] Has venue and it sits this many people: 50
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s): @freeformz
- [x] Has date : February 27th & 28th, 2016
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [x] Bridge Troll event made public; added event link to this thread
- [x] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [x] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [x] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by rachelmyers** [comment]
Do you need help finding volunteers or is do you have plenty of people??

**Comment by carlisia** [comment]
Hi @rachelmyers we would love help finding volunteers! How do you usually go about it?

**Comment by rachelmyers** [comment]
I can probably help! I'll wait until there's a Bridge Troll event (or other rsvp link) before I start pointing people to sign up. Will they need to attend a teacher training?

**Comment by carlisia** [comment]
@rachelmyers thank you! And, I'll get back re: teacher training.

**Comment by carlisia** [comment]
@rachelmyers I'm having a organizer training this Saturday at 1PM PST via Google Hangout with a couple of organizers. If you know of anyone interested in joining please let me know. It might turn into a teacher training session as well.

**Comment by rachelmyers** [comment]
I'll ask around. For clarification, if people definitely don't want to organize, but want to help TA and teach, will they feel like they're in someone else's meeting?

**Comment by carlisia** [comment]
@rachelmyers absolutely not! If anyone feels like that we would have to work to fix something! :)

We love having extra TAs in our workshops and hope they'll be inspired to become teachers. I don't know yet who will be teaching but we are in the process of figuring these things out.

**Comment by carlisia** [comment]
@allyvigil, I had a meeting with the organizers today. We are all set for February, will give you a specific date very soon. Please let us know: how many people would you like to cap the event at?

Once we get the date @freeformz is going to open and publish the Bridge Troll event.

Also, @jboursiquot is going to be helping move things forward, he is part of GoBridge.

@rachelmyers and everyone: we need to recruit more TAs and volunteers. So far we have @Randommood.

**Comment by tedyoung** [comment]
I'd like to volunteer, what's the best way for me to get involved?

**Comment by carlisia** [comment]
@tedyoung awesome! Let's wait for the organizers to figure out the date and publish the event on Bridge Troll, then you can sign up there to be a TA of volunteer.

We are going to have a organizer and a teacher training before the workshop and it will be noted here so anyone can join either session.

**Comment by allyvigil** [comment]
@carlisia Thanks so much for the update, and sorry I couldn't make the meeting. The event should be capped 50, to be safe.

**Comment by rachelmyers** [comment]
@carlisia, Yep! I'm happy to help recruit teachers and TAs, and I'll hold off until they can check the exact date and RSVP. :+1:

**Comment by freeformz** [comment]
Date is tentatively 2/27/2016 + 2/28/2016.

**Comment by freeformz** [comment]
Date is confirmed with @allyvigil

**Comment by jboursiquot** [comment]
Organizer/Teacher training scheduled for Jan 23rd, 1pm EST.

**Comment by carlisia** [comment]
@tedyoung I'd love to see you getting involved. The workshop event signup is up, join in as a volunteer!
https://www.bridgetroll.org/events/239

**Comment by tedyoung** [comment]
@carlisia I may have a conflict on Day 2 of the workshop, is it still helpful if I only volunteer for day 1?

**Comment by freeformz** [comment]
@tedyoung Yes!

**Comment by tedyoung** [comment]
@freeformz Cool. Volunteered!

**Comment by tedyoung** [comment]
I noticed the Org/Teacher training is tomorrow, where would I find details? @jboursiquot?

**Comment by jboursiquot** [comment]
@tedyoung I've invited you to the hangout. Just as a heads up, the first half is focused on organizer preparedness. We'll get into the teacher/TA side of things in the second half.

**Comment by jboursiquot** [comment]
Update: We conducted Organizer Training today. There was not enough time for Teacher Training. We'll need to pick a date to get both Teachers and TAs on the same hangout as the material will be relevant to both.

**Comment by jboursiquot** [comment]
@freeformz: we should pick a date that's a couple of days or so ahead of your workshop (or as soon as you have all your volunteers) to do a hangout for Teacher Training. Once we have the date, we'll publicize it on your BridgeTroll event page, similarly to how the Chicago RailsBridge has done for their [workshop](https://www.bridgetroll.org/events/242).

**Comment by dmitshur** [comment]
Hi, pardon the intrusion, but I wanted to ask something here because I couldn't quite find a definitive answer on the http://golangbridge.org/ site.

I'm someone who knows Go quite well and enjoys teaching others (assuming they're interested in learning), and I've heard (vaguely over twitter, etc.) that GoBridge may be looking for volunteers to teach/mentor people. I can't help organize workshops (being 1 person), but I'd love to join in some existing event if there's an opportunity for me to fill in a gap and help people learn Go or programming in general (or at least give it a try).

It looks like this event is happening in SF pretty soon, so it may be too late, and that's okay. But just in case it's possible, could someone please point me in the right direction where I could learn more, etc.?

Thanks!

**Comment by timblair** [comment]
Hi @shurcooL!  Thanks for reaching out: it's always brilliant to have more people willing to help out.

This SF event is scheduled for [this coming weekend](https://www.bridgetroll.org/events/239).  The event is being organised by @freeformz, so he's the best person to speak to about that event specifically.  He's probably also a good person to chat to about other SF events in general (we don't have a central list of "people who'd like to volunteer.")

It might be worth you looking over the information in our [organizing](https://github.com/gobridge/organizing) and [workshop-material](https://github.com/gobridge/workshop-material) repos here on GitHub to give you an idea on how we organise and run the workshops.

**Comment by dmitshur** [comment]
Thanks for the info @timblair, I'll read up on those links and ask @freeformz how the situation is looking for the SF event this weekend. :+1:

**Comment by freeformz** [comment]
@shurcooL I see you found yourself to the #gobridge channel, which is what I was going to suggest to you.
