### ISSUE TITLE
London Go Workshop - Jan/16 - Venue: Cloudflare

### ISSUE THREAD

**Issue by virtualsue** [gobridge/workshops#21]
Venue: Cloudflare, 25 Lavington St London SE1 0NZ, they will also provide food/refreshments
Date: 16 Jan 2016 11am - 5pm
Workshop is targeted for women, beginners on up. More experienced developers will be paired with beginners as much as possible. I have at least 2 volunteers helping me organise.
### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment]
Hi @virtualsue this is great. Please start filling in the details you already have in a new BridgeTroll event: https://www.bridgetroll.org/

Will you be able to teach the workshop or have people who can?

**Comment by virtualsue** [comment]
Nicola and I are planning to teach it.

**Comment by carlisia** [comment]
Ok @virtualsue, all you need to open up registration is to make sure there is content you can teach from and create the Bridge Troll event.

**Comment by carlisia** [comment]
Hi @virtualsue now that you have a date, let's get the BridgeTroll setup so we can start announcing it.

Also, would you and Nicola be available this Saturday for a teacher training via google hangout?

**Comment by carlisia** [comment]
@virtualsue January is fast approaching, let's get this event up on Bridge Troll so people can start signing up! Also, I'd love to include a link to it in our December newsletter!

**Comment by carlisia** [comment]
Hi @virtualsue, I saw your message but now can't find it where it was. No worries, and thank you for keeping us posted. Life gets busy and this is not supposed to be stressful :)

When you have bandwidth please touch base again. For now I'm gonna go ahead and close this.
