### ISSUE TITLE
Sao Paulo, SP - Date Feb 27 2016 - Course: Building Web Apps With Go - Venue: Impacta

### ISSUE THREAD

**Issue by seriallink** [gobridge/workshops#22]
Organizers: @seriallink, @vsouza, @vdemario, @marcosinger
Venue: Impacta [http://www.impacta.edu.br]
Date: Feb 27
Curriculum: Building Web Apps With Go - Em Portugues
### Logistic items
- [x] Has venue and it sits this many people: 40
- [ ] Has sponsor for food and drinks ( dropped )
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date February 27th & March 5th, 2016
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [x] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [x] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [x] Confirmed venue and date
- [x] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment]
@seriallink, @vsouza, @vdemario, @marcosinger, atualizacao: uma vez que decidirem o numero maximo de participantes (dependendo do local e da preferencia dos professores) e terminarem toda as questoes de logistica, podem abrir o evento no Bridge Troll com toda a info e publicar.

Vamos ficar de olho caso o Bridge Troll apresente algum tipo de impedimento por conta de nao ter localizacao. Nos informe por favor nao somente isso mas sobre qualquer oportunidade pra melhorias.

Eu marquei o item de `treinamento com organizadores` como completo, mas como falamos podemos fazer novamente, ateh porque nao deu tempo de finalizar.

De uma forma ou de outra eh necessario os organizadores revisarem o material aqui: https://github.com/gobridge/workshop-material e lembrar de usar como checklist, ainda mais nos dias do evento.

Eu estou devendo subir uma ou duas apresentacoes.

Obrigada!

**Comment by marcosinger** [comment]
estamos aguardando a reunião do @seriallink com o pessoal da Impacta ( 15/12 - terça-feira ) para definir os próximos passos

**Comment by carlisia** [comment]
@seriallink, @vsouza, @vdemario,

Caros, a intencao ainda eh fazer o workshop em fevereiro? Os unicos items pendentes para podermos criar e comecar a divulgar o evento sao data e patrocinador para o almoco (e after party se for ter). Como posso ajudar?

**Comment by vdemario** [comment]
@carlisia Ainda é sim, no final de fevereiro. Só não batemos o martelo ainda pq o pessoal da Impacta queria fazer um meetup normal antes do workshop. Vamos fazer um hangouts pra fechar as datas, provavelmente amanhã.

**Comment by carlisia** [comment]
:+1:

**Comment by marcosinger** [comment]
@seriallink @vdemario @carlisia 
Atualizada as datas do evento. Aguardando para o contato sobre o coffee break e reuniões de treinamento dos professores.

**Comment by nubunto** [comment]
Queria participar, mas não sou de São Paulo e parece que screencast não vai rolar ):

**Comment by marcosinger** [comment]
atualizei a quantidade de pessoas e abri o evento no meetup do GoBridge
