### ISSUE TITLE
Belo Horizonte, MG - Date 2016 - Course: Building Web Apps With Go - Venue: The Plant Coworking

### ISSUE THREAD

**Issue by paulohp** [gobridge/workshops#23]
Organizers: @paulohp @anapaulagomes

Venue: The Plant Coworking 

Date: 2016/01/16

Curriculum: 
### Logistic items
- [x] Has venue and it sits this many people: 40
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by marcosinger** [comment]
hey @paulohp .. I'm glad to see other workshops in Brazil.
Let me know if you need any help to make it happen

**Comment by carlisia** [comment]
@paulohp checa seu inbox, enviei um email com perguntas! c/c @anapaulagomes

**Comment by carlisia** [comment]
Closing for lack of response. Please let us know if we can help at all with this or future workshops!
