### ISSUE TITLE
San Diego, CA - Date May 21-22 2016 - Build Web Apps with Go - Venue: LEARN

### ISSUE THREAD

**Issue by gdey** [gobridge/workshops#26]
Organizers: @carlisia, @gdey

Venue: LEARN http://www.learnacademy.org/

Date: May 21st and 22nd

Instructor: @ardan-bkennedy, @gdey

Curriculum: Build Web Apps With Go
### Logistic items
- [x] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [x] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [x] Bridge Troll event made public; added event link to this thread
- [x] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [x] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment]
https://www.bridgetroll.org/events/253

**Comment by carlisia** [comment]
Done!
