### ISSUE TITLE
Louisville, Ky: 9/30

### ISSUE THREAD

**Issue by jesselucas** [gobridge/workshops#28]
Organizers: @jesselucas

Venue: @forestgiant

Date: 9/30

Curriculum: TBD, but an introduction.
### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [ ] Has teacher(s)
- [x] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment]
Hey @jesselucas, so awesome that you want to do this. It seems that you need a teacher and content, is that it?

**Comment by jesselucas** [comment]
@carlisia, I think so. A more experience teacher would be awesome but if we can't find anyone I would be willing to give it a try. Definitely need help/advice for content.

**Comment by dlsniper** [comment]
Hi, anything I could do to help out with this?

**Comment by jesselucas** [comment]
@dlsniper Thank you! I'll message you on Gopher Slack to catch you up with our progress.

**Comment by dlsniper** [comment]
@jesselucas hi there, any changes on this? Should we try again and give the workshop?

**Comment by jboursiquot** [comment]
Ping. How can we help move this forward?

**Comment by jboursiquot** [comment]
Closing. We can re-open if it seems likely.
