### ISSUE TITLE
Berlin 13/09 27/09 11/10 25/10 08/11 22/11 

### ISSUE THREAD

**Issue by Pisush** [gobridge/workshops#29]
Organizers: Natalie Pistunovich

Venue: Soundcloud HQ, Berlin

Date: 2nd and 4th Wednesday of the month, September - November, including. 
i.e. 14/09 28/09 12/10 26/10 09/11 23/11
Hours: 19:00-21:45

Curriculum: Go Tour in September -> content based on the Gopher Book
### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [x] Conducted organizer training
- [x] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by Pisush** [comment]
Changed location to Soundcloud and days to Wednesday.

They will provide drinks and snacks

I have 3 instructors on board, maybe more will join

**Comment by dlsniper** [comment]
This one has concluded. Thank you @Pisush, looking forward for the next one!
