### ISSUE TITLE
London, UK - Jan 28, Feb 04, Feb 11 - NOTHS

### ISSUE THREAD

**Issue by eggya** [gobridge/workshops#30]
Organizers: Eggya Chiquita

Venue: Notonthehighstreet - Richmond, London - UK

Date:     
 * installfest 27 January 2017
 * workshop 28 Jan, 04 Feb, 11 Feb

Curriculum: TBD - more likely to be introduction / beginner session, something that would be engaging for graduates / juniors.
### Logistic items
- [X] Has venue and it sits this many people: _25_
- [X] Has sponsor for food and drinks
- [X] Has organizer(s)
- [X] Has teacher(s)
- [X] Has date
- [X] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [X] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [X] Included in the event description if bikes are allowed inside or not (ask venue)
- [X] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [x] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [x] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [x] Conducted organizer training
- [x] Conducted teacher training
- [x] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [x] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by dlsniper** [comment]
Hi @eggya,

Thank you for opening this.
When could we have a quick chat to catch up about this even and startup with preparations?
Please ping me on Gophers Slack (@dlsniper) or e-mail: florin[at]golangbridge [...] org.
Looking forward to talk with you.

Kind regards,
Florin

**Comment by ardan-bkennedy** [comment]
@dlsniper I have been communicating with @eggya on this. Let me catch you up on Slack and I would love to help you on this workshop.

**Comment by eggya** [comment]
Thank you @ardan-bkennedy & @dlsniper for your support, I'm really excited about this workshop. I'll try to say hi to @dlsniper today.

**Comment by dlsniper** [comment]
Here's the summary of the discussion we've had yesterday on Hangouts:
- the course will be held across 3-4 weekends on Saturdays, probably for at least 6 hours each time
- It is designed for new programmers, with very little programming experience
- the target group for attendance is young women graduates
- the venue can host around 20-25 participants
- there are at least two possible teachers for this as well as two teaching assistants
- this should be done in collaboration with the Women Who Go London chapter

Things to do going forward:
- for organizer:
  - [ ] choose the dates and final format for the workshop
  - [ ] create the Bridge Troll class
  - [ ] find (more) sponsors for the event
  - [ ] organize catering
- for GoBridge:
  - [ ] provide the training material
  - [ ] provide the organizer presentation
  - [ ] provide the teacher presentation (when teachers are confirmed)
  - [ ] promote the event
  - [ ] try and help out with finding sponsors by using various available channels of communication

@eggya please let me know if I'm missing any details. Looking forward speaking to you again.

**Comment by dlsniper** [comment]
Done
