### ISSUE TITLE
Vancouver, BC

### ISSUE THREAD

**Issue by gh-osama** [gobridge/workshops#33]
Organizers:
GolangVan/Osama Khan

Venue:
Hootsuite HQ
5 E 8th Ave, Vancouver, BC V5T 1R6

Date:
Sometime towards end of March or beginning April based on teacher availability

Curriculum:
Ultimate Go by Bill Kennedy

### Logistic items
- [x] Has venue and it sits this many people: 80
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by gh-osama** [comment]
[Progressa](http://www.progressa.com) has confirmed sponsorship on an ongoing basis conditional to getting further budget details.

- Need GolangBridge support for Teachers.

**Comment by dlsniper** [comment]
as per @ardan-bkennedy recommendation, this now closed as it wasn't a GoBridge event but rather a generic one.
