### ISSUE TITLE
New York, NY - WWG NY - Ultimate Web - 5/20 && 5/21

### ISSUE THREAD

**Issue by jcbwlkr** [gobridge/workshops#36]
Organizers: @ardan-bkennedy from Ardan and @lyoness of Women Who Go NY

Venue: Packet

Date: Saturday and Sunday 5/20 and 5/21

Curriculum: Ultimate Web from Ardan Labs taught by @jcbwlkr

### Logistic items
- [x] Has venue and it sits this many people: _20_
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by dlsniper** [comment]
Yaaay! Thank you for this, I'll contact you in the weekend for more details.

**Comment by jacobsmith928** [comment]
@jcbwlkr still looking for a venue?  Maybe we @packethost can help!

**Comment by jcbwlkr** [comment]
@jacobsmith928 hello! Yes, that would be great! We still need a venue and a sponsor for refreshments. If @packethost could help with either of those I would be eternally grateful. I am not based in NY and I know literally nothing about available venues there lol

**Comment by jacobsmith928** [comment]
@jcbwlkr how many people do you want to host and what's the space setup you need?  We could def make available our office (next to the WTC) and host you there.  Maybe we could talk voice to coordinate and see if it's a good fit?

**Comment by jcbwlkr** [comment]
@jacobsmith928 I'll email you

**Comment by Lyoness** [comment]
Once venue is confirmed. I can add details to Women Who   Go NYC meetup page.

Do we want to invite all gophers? Just women gophers? Underrepresented groups? What is the intemded attendee demographics?

**Comment by ardan-bkennedy** [comment]
Just groups the GB can serve please. However, if someone does not fit the profile, they can attend if they bring someone with them. 

Sincerely,
Bill Kennedy

**Comment by Lyoness** [comment]
Event has been posted!  
https://www.meetup.com/NYC-Women-Who-Go/events/239306971/

**Comment by jcbwlkr** [comment]
@Lyoness sweeeeet! I think the last thing we need is a sponsor for food and drinks. Can you think of anyone around NY to ask?

**Comment by Lyoness** [comment]
@jcbwlkr :  ah ok @jacobsmith928 Packet HQ is hosting the Space with food and drinks separate?  Let me put a call to fellow Women Who Go and NYCGolang orgs...

**Comment by jacobsmith928** [comment]
Hey @jcbwlkr how we looking for all the things?  Need anything else from our end?

**Comment by jboursiquot** [comment]
Hey gang. Did this ever materialize? Just checking if I can help if needed.

**Comment by jcbwlkr** [comment]
Oh, yes we had the event and it was great! I'll go ahead and close this out.
