### ISSUE TITLE
London, UK - WWG London - BWAG - May '17

### ISSUE THREAD

**Issue by eggya** [gobridge/workshops#37]
Organisers: 
 - Eggya Chiquita (@eggya)
 - Jimena Cabrera Notari (@phenomenes)

Venue: Pusher office, London - UK
Date: 3 June 2017
Curriculum: BWAG

### Logistic items
- [X] Has venue and it sits this many people: 15
- [X] Has sponsor for food and drinks
- [X] Has organizer(s)
- [X] Has teacher(s)
- [X] Has date
- [X] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [X] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [X] Included in the event description if bikes are allowed inside or not (ask venue)
- [X] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by eggya** [comment]
We've updated the dates and created event draft on BridgeTroll, is there anything else you need from us?

**Comment by jboursiquot** [comment]
Hi @eggya. Just doing some clean up. Can I assume this event already took place?

**Comment by eggya** [comment]
Hello, yes - this has been done.
