### ISSUE TITLE
Norfolk, VA

### ISSUE THREAD

**Issue by kaxcode** [gobridge/workshops#42]
Organizers: Linda Nichols, Kenia Valladarez
Venue: Percolator (Co-working space in downtown Norfolk, VA)
Date: Saturday Sep 22, 2018
Curriculum: Intro to Go (1-day event with Go Challenges)

### Logistic items
- [x] Has venue and it sits this many people: 20
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [x] Included in the event description if bikes are allowed inside or not (ask venue)
- [x] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hi @kaxcode! Thank you for getting this started. I'm one of the core member of GoBridge and can assist you as needed. If you want to hop on a hangout and talk through some of the logistics of running a workshop, I'm happy to. We're in the same timezone too! I'm in Ellicott City, MD.

**Comment by ardan-bkennedy** [comment]
Hi @kaxcode. Are you still working on this event? Let's talk when you have the time.

**Comment by kaxcode** [comment]
Hi @ardan-bkennedy. Yes, the event is still on. I just haven't picked a curriculum 😅.

**Comment by ardan-bkennedy** [comment]
Are you on Gopher Slack? I would love to chat/speak when you have a moment.

**Comment by ardan-bkennedy** [comment]
Hi @kaxcode can we touch base again. I am looking at my september calendar.
