### ISSUE TITLE
Fresno GO Bridge Workshop

### ISSUE THREAD

**Issue by psettle87** [gobridge/workshops#45]
Organizers:

Venue:Bitwise or Root Access Hackerspace

Date:

Curriculum:

### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [ ] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hi! Thanks for stepping up to organize this event.

I'm happy to get on a Google Hangout to walk you through the process and get you up to speed on what you'll need to know. Interested?

**Comment by jboursiquot** [comment]
Ping!

**Comment by psettle87** [comment]
Hey Johnny,

What dates and times work for you?

**Comment by jboursiquot** [comment]
Hey @psettle87, could you do tomorrow (4/18) at 2pm EDT?

**Comment by jboursiquot** [comment]
Ping!

**Comment by ardan-bkennedy** [comment]
Hi @psettle87. Are you still working on this event? Let's talk when you have the time.

**Comment by jboursiquot** [comment]
@psettle87 @ardan-bkennedy did you work out next steps?

**Comment by psettle87** [comment]
I am not moving forward with this project at this time.
