### ISSUE TITLE
Portland, OR 

### ISSUE THREAD

**Issue by brainsnail** [gobridge/workshops#47]
Organizers: Logan Davis

Venue: [Puppet HQ - 308 SW 2nd Ave, Portland, OR 97204](https://puppet.com/)

Date: September 15th / September 16h

Curriculum: [Ultimate Go](https://github.com/gobridge/workshops/blob/master/available_courses.md#ultimate-go) provided by Bill Kennedy

### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [x] Assignee added event date -1 week to calendar as reminder

### Presentations
- [x] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [x] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [x] Confirmed venue and date
- [x] More rounds of announcements on social media. Mention how many spots left

**Comment by abankspdx** [comment]
Did this end up happening? And if not, do you think it'd be worth a shot to try again?

**Comment by brainsnail** [comment]
Yep, it did happen!

I would definitely be interested in helping put together another one at some point as well.

**Comment by abankspdx** [comment]
Do you have a timeline in mind? I would like to help, mostly because it's an event I'd also really like to go to. Feel free to email me if you're interested in coordinating @ alex.banks0@gmail.com
