### ISSUE TITLE
Albany, NY

### ISSUE THREAD

**Issue by erkattak** [gobridge/workshops#49]
Organizers:
Mitch Patterson
Mavreen Smiel
Francois Rice 
Blain Smith
Erik Straub

Venue:
Rensselaer Polytechnic Institute (RPI)
Troy, NY 12180

Date: 2/2-2/3/2019

Curriculum: Ultimate Go

### Logistic items
- [x] Has venue and it sits this many people: 40
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)  
https://www.eventbrite.com/e/capital-district-gobridge-ultimate-go-tickets-52406438067
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by ardan-bkennedy** [comment]
This is Brilliant!!!!  Tell me how I can help if/when you need it.

**Comment by ardan-bkennedy** [comment]
Don't worry about BridgeTroll. Use your meetup page or Eventbrite

**Comment by erkattak** [comment]
Awesome! Thanks Bill. Also, @blainsmith says hi

**Comment by ardan-bkennedy** [comment]
I have 12/8 and 12/9 open. I would love to see what you are doing if you end up holding an event those dates!

HI @blainsmith!!

**Comment by blainsmith** [comment]
Hi @ardan-bkennedy!

This will be good for the local community. We have some good contacts and local colleges and universities that would benefit greatly from this!

**Comment by erkattak** [comment]
@ardan-bkennedy what is your availability in January? RPI has asked that we consider mid-December is finals time, so we're thinking of moving it until at least mid-January when students are back. This likely affects other local schools, as well.

**Comment by erkattak** [comment]
@ardan-bkennedy Blain mentioned the weekend of Feb 1 being available, so if it works for you we'd like to lock down 2/2 and 2/3 as the days for the course.

**Comment by ardan-bkennedy** [comment]
It's in my calendar!  The key is we need to find a sponsor for my travel and room. Being in Miami this won't be expensive. Guessing a budget of $1500 to be safe but my guess is $1k should be more than enough.

**Comment by erkattak** [comment]
We're working on sponsorship and space now. The facility we're using would like to know general start/end times for the event. What would you suggest there?

**Comment by ardan-bkennedy** [comment]
9am - 5pm each day. We can go 10am - 6pm if that’s better for everyone.

**Comment by jboursiquot** [comment]
@brkattk This event happened, right?

**Comment by erkattak** [comment]
Yes, thanks!
