### ISSUE TITLE
If you want to be inclusive use LGBTQIA instead of LGBQA

### ISSUE THREAD

**Issue by campoy** [gobridge/workshops#5]
Context: https://github.com/gobridge/organizing

Leaving transexuals is wrong.

LGBTQ also sounds like a good solution since it's the most common acronym for the community.
LGBTQIA is the most inclusive one I know, but it might seem a bit excessive.

**Comment by ardan-bkennedy** [comment]
I changed changed LGBQA with LGBTQIA in the readme. Please let us know if you find anything else that needs to be changed. You can always issue a PR as well.
