### ISSUE TITLE
Denver, CO - Date : TBD 2018 Go Workshop Course : Ultimate Go

### ISSUE THREAD

**Issue by swesoc** [gobridge/workshops#52]
Organizers: None

Venue: Denver,CO

Date: TDB

Curriculum: Ultimate Go

### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [ ] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hey @swesoc. Did this happen or is it still in the works?

**Comment by swesoc** [comment]
Nope, not yet. Still waiting for it.

**Comment by jboursiquot** [comment]
@swesoc what do you need for next steps? I see the selected material is Ultimate Go. Have you already been in touch will Bill Kennedy?

**Comment by swesoc** [comment]
Thanks a lot for checking on this. I am not sure what would be the next step, mostly a sponsor is needed for this so that this event can take place. I am not in touch with Bill Kennedy when I open this issue, I was supposed to enter course details. I simply copied this one from some other thread as I liked the content.

**Comment by swesoc** [comment]
Another thing @jboursiquot, please let me know when does GopherCon 2019 US scholarship start, possibly the link. I wish to apply there. Thanks

**Comment by jboursiquot** [comment]
Hey @swesoc, apologies if I didn't follow up with you about this--or maybe Bill or I did via email.

In any case, let us know what the status is on this one so we can either close it or try to make it happen.

**Comment by swesoc** [comment]
Thanks, @jboursiquot for getting back. The status is just the same, possibly waiting for a sponsor.

**Comment by jboursiquot** [comment]
Hey @swesoc, just checking in. Do you need help finding a sponsor to move forward?

**Comment by swesoc** [comment]
Yup @jboursiquot that would be a great help. Thanks

**Comment by jboursiquot** [comment]
Okay. GoBridge can help get the word out for a sponsor. I'd love to get on a Hangout with you though to talk more about logistics and things. Got 30 minutes next week? Here's my availability: https://doodle.com/poll/tmzpwhamfzdw42rs

**Comment by swesoc** [comment]
Sorry for a delayed response. I booked the time next week. we can talk just that I don't think I can contribute much towards the logistics, I am basically a temporary lecturer.

**Comment by jboursiquot** [comment]
Great send me an email so I can send you an invite. johnny@gobridge.org

**Comment by jboursiquot** [comment]
Great chatting with you yesterday @swesoc. Let me know when you've settled on a good date and we'll start the hunt for venue+food sponsors.

**Comment by swesoc** [comment]
It was great talking with you too @jboursiquot. I am planning around October 12th or October 19th. Not sure if there is any Go event around that time. I have messaged one of the Go meetups organizers, just to check if any Go event around that time. let's see.

I had started this thread so that I can learn GO,   never thought I will be teaching in this event. It gonna be a whole new experience for me :).

Thanks

**Comment by swesoc** [comment]
@jboursiquot, sorry for the delayed response. I had messaged women Who Go Meetup organizers, trying to find about Go Meetup around Oct 12th. They had Golab planed,  I wanted to combine with it. But it looks like this would be more of presentation thing. Was waiting for dates but it is not yet clear. So I thought I will mail you dates that are good for GoBridge, I am good with either Oct 12th or Nov 16th. Let me know what works best for you and then we can start.

Thanks

**Comment by jboursiquot** [comment]
No worries @swesoc. Oct 12 might work. It gives us a month to get things lined up but we'll have to move quickly to get sponsorships within the next week or so in order to have enough time to promote the workshop. 

So as it stands today we still need a venue and food sponsors, correct?

**Comment by swesoc** [comment]
Yup @jboursiquot we also need Volunteers to teach GO.

**Comment by jboursiquot** [comment]
Update: Conversation started with Bitly as a possible venue. Stay tuned.

**Comment by anEXPer** [comment]
[Pivotal's Denver office](https://pivotal.io/locations/denver) would also be available as a venue for this event. We've had Railsbridge here in the past, I'm pretty sure we can make it work.

**Comment by jboursiquot** [comment]
That sounds really good @anEXPer. We’ve started a conversation with Bitly and will see where that takes us. Regardless, it’s good to know Pivotal is option and we’ll absolutely be taking advantage of that.

**Comment by ardan-bkennedy** [comment]
@jboursiquot what is the status of this event?
