### ISSUE TITLE
Seoul, South Korea

### ISSUE THREAD

**Issue by wooseopkim** [gobridge/workshops#53]
Organizers: Wooseop Kim, Aerin Lee, Yeonju Lee, and 9 more

Venue: 

Date: Feb 2018 (tent.)

Curriculum: Developing own one

### Logistic items
- [x] Has venue and it sits this many people: (30 expected)
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [x] Confirmed venue and date
- [x] More rounds of announcements on social media. Mention how many spots left

**Comment by wooseopkim** [comment]
We got a [D.CAMP](https://dcamp.kr) membership and found that Seolleung Center is available around the dates we'd like the workshop to be, which is third weekend of February. We're visiting the place in advance tomorrow. We also have a back-up plan for the place. It's very likely that we could confirm the date and venue soon, or in a few weeks.

**Comment by wooseopkim** [comment]
A little late report:
- Venue: Rm 308, Bldg 10-1, Seoul National University
- Participants: 30+ students and about 15 of our team
- Date: 16-17 Feb
- Course: done w/ making our own one

**Comment by ardan-bkennedy** [comment]
Brilliant! If you need anything please let us know.

**Comment by wooseopkim** [comment]
Everything was great. We had almost no issues during the workshop, and we'll soon start reviewing the feedback. Quick retrospective here: forgot about Bridge Troll and about parking space.
