### ISSUE TITLE
New York, NY  Go Workshop 2019

### ISSUE THREAD

**Issue by nywilken** [gobridge/workshops#55]
Organizers: Wilken Rivera, Kathryn Jonas

Venue:

Date: May 18th 2019

Curriculum: TBD (intermediate level Go) 

### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [ ] Has TAs
- [x] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on Meetup Groups
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
@nywilken let me know if I can be of assistance in any way for this workshop.

**Comment by brooksa321** [comment]
@nywilken If you need and TA, I'd be happy to come up

**Comment by Yigenana** [comment]
> @nywilken If you need and TA, I'd be happy to come up

@brooksa321 would love to have you TA if you're still available. If you could send me an email, I'll be sure to follow up with the details. kathrynjonas@gmail.com

**Comment by jboursiquot** [comment]
Done. Closing.
