### ISSUE TITLE
Monterrey, NL, Mexico - Go Bridge Workshop

### ISSUE THREAD

**Issue by eduartua** [gobridge/workshops#57]
Organizers: Eduar Tua

Venue: Boulevard Antonio L. Rodríguez 1888, Santa María, 64650 Monterrey, Nuevo Leon, Mexico

Date: Friday, March 22, 2019

Curriculum:

- Concurrencia vs Paralelismo
- Intro a WaitGroup
- Method Sets
- Condición Race
- Mutex
- Atomic

### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [x] Included in the event description if bikes are allowed inside or not (ask venue)
- [x] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [x] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [x] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [x] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [x] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hey @eduartua! Glad to see this. Let me know if you need any assistance on this. Happy to help.

**Comment by eduartua** [comment]
Thanks @jboursiquot usually I had problems with venue and food but I managed to find a Sponsor for this one. =)

**Comment by jboursiquot** [comment]
Awesome!

**Comment by jboursiquot** [comment]
Hey @eduartua! Did this take place?

**Comment by eduartua** [comment]
Yes, sir. This week I'll announce the next one.
