### ISSUE TITLE
Planning to start a New Group in Minneapolis MN (south west metro) 

### ISSUE THREAD

**Issue by anilkgg** [gobridge/workshops#58]
Sorry for this issue. There is no gobridge my area. I am planning to start new one. 
I am bit confused how to start? first I register on eventbrite or meetup group or is there a gobridge registration site. ?
Please help.
Thanks,
Anil
 
Organizers:

Venue:

Date:

Curriculum:

### Logistic items
- [ ] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [ ] Has organizer(s)
- [ ] Has teacher(s)
- [ ] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hey @anilkgg. Are you looking to start a Go user group that meets regularly or trying to organize a GoBridge workshop in your area? These aren't mutually exclusive but we want to direct you accordingly.

**Comment by anilkgg** [comment]
Start a Go user group which meet regularly + how to do Go Bridge workshop or involve with GDN? 
Thanks!

**Comment by jboursiquot** [comment]
Ok cool. GDN's currently onboarding existing and active user groups. We will have details and procedures for new groups in the coming weeks.

**Comment by jboursiquot** [comment]
You can still organize a GoBridge workshop in your area without an existing user group though just to be clear. Happy to help you make that happen when you're ready.

**Comment by anilkgg** [comment]
Awesome! Thanks for a quick response and support!
