### ISSUE TITLE
Toronto 🇨🇦 September 21, 2019

### ISSUE THREAD

**Issue by deniseyu** [gobridge/workshops#59]
Organizers: Denise Yu, Spike Lindsey, Zach Goldstein, Mike Fridman, Max Gonzih

Venue: TBD

Date: September 21, 2019

Curriculum:

### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [x] Included in the event description if bikes are allowed inside or not (ask venue)
- [x] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [x] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hi @deniseyu and thanks for stepping up to organize a workshop.

Part of my role is to support organizers like yourself throughout the process. I'm happy to get on a Hangout to talk through the steps and help you and your fellow organizers know what to expect.

If that sounds good, let's find a time in the next week or so to chat.

**Comment by deniseyu** [comment]
Thank you @jboursiquot, that would be really helpful! I can chat next week, let me ping the others to see if they can. By next week we will hopefully have a venue confirmed. I'll try to find you on the Gophers Slack to sort out a time.

**Comment by deniseyu** [comment]
@jboursiquot quick question - is it recommended to host an "install fest" sometime during the week before the workshop? For ClojureBridge I remember that we had a Friday evening optional event for attendees to make sure the laptops they planned to use were ready to go for Saturday morning. But maybe downloading Go or using a web-based IDE is a lot more straightforward than installing Clojure tools.

**Comment by jboursiquot** [comment]
@deniseyu honestly I think it would be helpful. Despite instructions sent weeks before the workshop, folks still tend to come in without Go installed or an IDE/text editor configured. If you can arrange to have an install fest ahead of the workshop, that would save us a ton of time on the day of.

**Comment by deniseyu** [comment]
I've started the draft event on Bridge Troll, just blocked on having Toronto added as a selectable chapter. Not sure if anyone other than me can see this, but it's at https://www.bridgetroll.org/events/483

**Comment by jboursiquot** [comment]
Done and done! Thanks again for leading the organization of this workshop @deniseyu. It was a great event and one we at GoBridge hope you and your co-organizers will hold regularly in your community.
