### ISSUE TITLE
Intro to Programming w/ Go Workshop for Girls Inc. in San Diego

### ISSUE THREAD

**Issue by animalchinster** [gobridge/workshops#62]
Organizers: ID Analytics (Symantec) in conjunction with Girls Inc. (https://girlsinc.org/). Contacts are Brandon Chin (animalchinster@gmail.com) (SDE @ ID Analytics) and Frelisa Cretain (Frelisa_Cretain@symantec.com) (Aministration Manager @ ID Analytics, IDA's point of contact for Girls Inc.).

Venue: ID Analytics (15253 Avenue of Science, San Diego, CA 92128)

Date: October 17th, 2019

Curriculum: Introduction to Programming (using Go)

### Logistic items
- [x] Has venue and it sits this many people: 20
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [ ] Has teacher(s)
- [x] Has date
- [ ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jboursiquot** [comment]
Hey @animalchinster! Glad to see this.
Is there anything I can help you with to help you successfully organize this workshop? 
I'm happy to get on a Hangout to chat and answer specifics around the process and what to expect.

**Comment by animalchinster** [comment]
@jboursiquot Hi Johnny, I appreciate the response. A Google hangouts so we can chat would be great, thanks!

**Comment by jboursiquot** [comment]
Great! Grab a 30-min slot here https://doodle.com/poll/tmzpwhamfzdw42rs and shoot me an email so I can send you an invite. johnny@gobridge.org

**Comment by jboursiquot** [comment]
Great chat today @animalchinster. As we discussed, let me know when you have the grant numbers and when you've filed the BridgeFoundry application.

For reference: 
- https://operations.bridgefoundry.org/grants/seed-grants/
- https://operations.bridgefoundry.org/using-funds/approved-expenses-policy/

I look forward to providing feedback on the material you put together.

**Comment by animalchinster** [comment]
Hi @jboursiquot, we recently got the numbers for transportation and hardware costs, and I've submitted a BridgeFoundry grant application. For reference, I'm attaching the quotes I received for each of the items.
[girls-inc-workshop-transportation-quote.pdf](https://github.com/gobridge/workshops/files/3591934/girls-inc-workshop-transportation-quote.pdf)
[girls-inc-workshop-chargers-estimate.pdf](https://github.com/gobridge/workshops/files/3591936/girls-inc-workshop-chargers-estimate.pdf)

**Comment by animalchinster** [comment]
Hey Johnny,

Would it be possible to book some more time to chat with you? I want to
talk about the sustainability of what I want to do and how to ensure that I
can make this continue to live after this particular workshop.

Thanks,
Brandon

**Comment by jboursiquot** [comment]
@animalchinster absolutely! Let's chat. I have some time today if you can make it happen. I'll send you an invite and we can change it to a date/time that works for both of us.

**Comment by carlisia** [comment]
@animalchinster at what time would this workshop happen?

**Comment by animalchinster** [comment]
> @animalchinster at what time would this workshop happen?

Hi @carlisia, we are currently planning to have it run from about 2:00PM - 5:00PM.

**Comment by carlisia** [comment]
I'm in SD, but it would be a bit tough for me to make it there during the week and during work hours and help out. 

Unless you have a set group, in other words, if you want help putting the word out to get more attendees, I can help with that.

**Comment by ardan-bkennedy** [comment]
@carlisia @jboursiquot  What is the status of this event?

**Comment by carlisia** [comment]
It looks like it fell through. We wouldn't be doing in person workshops at the moment either.

**Comment by ardan-bkennedy** [comment]
We can hold an online workshop?

**Comment by carlisia** [comment]
I'm game.

**Comment by ardan-bkennedy** [comment]
Ok, Let's identify a date, topic, and who can attend. Then we can figure out next steps.
