### ISSUE TITLE
Learn to Code with Go | Baltimore, MD

### ISSUE THREAD

**Issue by jboursiquot** [gobridge/workshops#63]
Organizers: Johnny Boursiquot
Venue: [SmartLogic](https://smartlogic.io/) (3500 Boston St #323, Baltimore, MD 21224)
Date: December 7th, 2019
Curriculum: Practical Go

### Logistic items
- [x] Has venue and it sits this many people: ___
- [x] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](http://bit.ly/gobridge-practical-go-workshop)
- [x] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [x] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [x] Bridge Troll event made public; added event link to this thread
- [x] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [x] First social media announcement's gone out
- [x] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [x] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [x] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [x] Confirmed venue and date
- [x] More rounds of announcements on social media. Mention how many spots left

**Comment by mastermndio** [comment]
Let me know if you need a TA

**Comment by jboursiquot** [comment]
I'd love to have you @mastermndio.

**Comment by jboursiquot** [comment]
Forgot to close this one. Workshop took place. 🎉
