### ISSUE TITLE
GoBridge Worldwide!

### ISSUE THREAD

**Issue by mastermndio** [gobridge/workshops#69]
Interested in running a remote GoBridge Workshop. wasn't sure if this was allowed?

Organizers: Aaron Brooks

Venue: Combination of Twitch + Slack + Zoom(This would be optional, but breakout rooms could be really beneficial for collaboration so people arent learning alone)

Date: Saturday September 1

Curriculum:

### Logistic items
- [ X ] Has venue and it sits this many people: Unlimited to watch. Zoom sessions are Max of 500 for anyone choosing to interact
- [ ] Has sponsor for food and drinks (Not applicable to to being remote, though I am working on GrubHub discount codes)
- [ X ] Has organizer(s)
- [ X ] Has teacher(s)
- [ X ] Has date
- [ X ] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by mastermndio** [comment]
The Twitch channel this would be hosted on would be  https://twitch.tv/mastermndio

**Comment by ardan-bkennedy** [comment]
We have a zoom accoun that supports up to 500 people on a webinar. You can have a meeting and webinar. Not sure what would work better for you. You can request a host link with this form (https://airtable.com/shrsSH1on1BjbjTNi).

Don't worry about BridgeTroll. I would post things on Meetup for the RSVP. If you are not working with a meetup group, we can use the GoBridge meetup account. Let me know if you want to do that.

Let me ping @jboursiquot to see if he has time to help and if not I will assign myself to his issue. 

In the meantime, do you need anything else?

**Comment by jboursiquot** [comment]
Hey @mastermndio, totally cool with putting an online workshop together. As @ardan-bkennedy mentions, we do have a Zoom account suitable for this, complete with the breakout functionality.

I'm happy to facilitate getting the meeting booked on Zoom. We should use Meetup to manage registrations and the sharing of the meeting room link to participants--similar to how we do it for a regular online meetup event.

We can run the event through the [Baltimore Go Meetup Group](https://www.meetup.com/BaltimoreGolang/) which would take care of pretty much all costs associated with meetup/zoom since it's part of the Go Developers Network.

How does that sound?

**Comment by mastermndio** [comment]
I got caught up with tons of other stuff and didn't get around to fully planning this. My schedule has opened up and I want to run this Saturday October 24. @jboursiquot I think the things you outlined sound super helpful if still an option.

**Comment by ardan-bkennedy** [comment]
Hi @mastermndio, we have a zoom account that we can use so no worries there.

Send an email to Jared Davis <jared.alexander.davis@protonmail.com> and let him know you are looking at performing a workshop and not just a meetup. There is a form to request a zoom event (https://airtable.com/shrsSH1on1BjbjTNi) but it's important Jared knows you need more time scheduled.

We have a Meetup account for GoBridge (https://www.meetup.com/gobridge/) so we can use that account to announce the event and get RSVP. If @jboursiquot want to run things through the Baltimore Meetup account that is fine as well.

Let me know what else you need.

**Comment by jboursiquot** [comment]
@mastermndio Go through the request form to get a zoom URL from Jared. Once we have that, we can use the B'more Meetup to set up the event and manage RSVPs, etc.

**Comment by ardan-bkennedy** [comment]
@mastermndio @jboursiquot  What is the status of this event?
