### ISSUE TITLE
Brussels, Belgium: 1 Feb 2016, Go workshop, Location TBD

### ISSUE THREAD

**Issue by luna-duclos** [gobridge/workshops#7]
Organizer: @PSG-Luna (Though I really could use some help)
Venue: TBD
Date: 1 Feb 2016
Curriculum: TBD

This is the day after FOSDEM, so I'm hoping we can have a full room
- [ ] Need sponsor for venue
- [ ] Need sponsor for travel
- [ ] Need sponsor for catering

**Comment by ardan-bkennedy** [comment]
This is excellent @PSG-Luna. Veronica will be reaching out soon. Yea !!!

**Comment by carlisia** [comment]
Closing this for now. We'll reopen it when we are ready to move forward.
