### ISSUE TITLE
Remote 3-day introduction to Go

### ISSUE THREAD

**Issue by jub0bs** [gobridge/workshops#70]
Organizers: Julien Cretel ([@jub0bs](https://twitter.com/jub0bs))

Venue: remote (on Jitsi)

Date: 13-15 January 2021 (9am-5pm, GMT+1)

Curriculum: https://www.humancoders.com/formations/go#outline (outline in French, though the course would likely be given in English, if people who speak English but not French register)

### Logistic items
- [x] Has venue and it sits this many people: at most 6
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels) (same audience as Ultimate Go)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)

### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [ ] Self-assigned the issue
- [ ] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jub0bs** [comment]
I've long hesitated before opening this issue, because I usually give my course to no more than six participants (the course involves a lot of practice) and I tend to give it remotely rather than physically, these days. This would be my first GoBridge event, but it seems to me that the GoBridge event template is geared towards a bigger crowd and on-site events... Let me know.

**Comment by jboursiquot** [comment]
Hi @jub0bs and thanks for volunteering your time for this.

Yes, the template needs some tweaks to make it more suitable for online events--thanks for the feedback.

Also, you can safely ignore the part about posting the event to Bridge Troll (another update for the template).

Are you part of an online Go meetup by chance? Is it managed through the Go Developer Network (GDN) Meetup.com account? I ask because that might be the easiest and most efficient way to post the event details and accept registrations. Let me know and we'll go from there.

**Comment by jub0bs** [comment]
@jboursiquot Thanks for your reply. Sorry for getting back to you so late. I stayed away from emails over Xmas.

> Are you part of an online Go meetup by chance?
> Is it managed through the Go Developer Network (GDN) Meetup.com account? I ask because that might be the easiest and most efficient way to post the event details and accept registrations. Let me know and we'll go from there.

No, I'm afraid. I'm not a big fan of Meetup as a platform, to be honest. Also, I've just moved to a new place and there has been no IRL meetups there since then due to the health crisis.

I understand that you want to use a platform like Meetup for transparency purposes, correct? Let me know.

All the best, and Happy New Year!

**Comment by jub0bs** [comment]
I'll figure something out. It's better to close this issue. Thanks anyway.

**Comment by ardan-bkennedy** [comment]
Why are you closing this event? Let's talk, DM me on slack or email.

**Comment by jub0bs** [comment]
@ardan-bkennedy I had to postpone the event for various reasons. Also, not a big fan of using Meetup as a platform for registration.

**Comment by ardan-bkennedy** [comment]
Since this is a free event, using Meetup is in line with our use of Meetup for the GDN.  Let's talk over email at some point because I think it would be valuable for the community to have you teach a workshop.
