### ISSUE TITLE
Remote 3-day introduction to Go

### ISSUE THREAD

**Issue by jub0bs** [gobridge/workshops#72]
Organizers: Julien Cretel ([@jub0bs](https://twitter.com/jub0bs))

Online: on Jitsi

Date: June 29th to July 1st 2021 (9am-5pm, GMT+1)

Curriculum: https://www.humancoders.com/formations/go#outline (in French)

We'll cover the fundamentals of the language, from a "Hello, World!" program all the way to the concurrency aspects, as well as some Web client and server code. A mini-project (a tool for checking the validity and availability of usernames on multiple platforms) will serve as a forcing function for introducing new concepts as we go. Emphasis is placed on practice (mini-project and and supporting exercises).

The material (slides) is in English, but the course will be given through French.

### Logistic items
- [x] Sits this many people: at most 8
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels) (Other Programming Experience)
- [x] Draft of event started under a Meetup.com account managed by the Go Developer Network (GDN)--typically your local Go user group's online meetup.

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all applicable tasks above are completed:exclamation:)

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [ ] Google Hangout scheduled (if this is a first timer or when applicable)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Published and announced Meetup event with open registration
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training (if applicable)
- [ ] Conducted teacher training (if applicable)
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by jub0bs** [comment]
Note that, although this event will take place online, because it place emphasis on practice and exercises, I can only accept a limited number of participants.

**Comment by jboursiquot** [comment]
Hey @jub0bs, seems like the course is a paid one. Will you have discount codes for students to register for free?

**Comment by jub0bs** [comment]
Hey @jboursiquot. Sorry about the confusion! The course is normally a paid one, but I only link to the course page for the syllabus. I'm giving this session **for free**, so no need for discounts at all :) 

If it's too confusing, I can remove the link from the description and replicate the syllabus in this issue. Let me know.

**Comment by jub0bs** [comment]
The date is drawing closer and I'm anxious to start advertizing the event on social media... Is there anything preventing me to do so?

**Comment by jboursiquot** [comment]
@jub0bs: yes, we should be able to advertise this. One thing that's not clear on yet is how students will register. We usually use meetup.com to manage this and collaborate with an existing meetup group (whichever's your "local" meetup) to track registrations. Is meetup what you had in mind or something else?

**Comment by jboursiquot** [comment]
Hey @jub0bs will you be using a Meetup group event announcement and registration as recommended?

**Comment by jub0bs** [comment]
@jboursiquot Sorry about the delay. I'm not close to any Meetup group, but I've reached out to the Paris one to see if we can work something out about this. Stay tuned.

**Comment by jub0bs** [comment]
@jboursiquot I reached out to Diana Ortega from Women Who Go Paris, who was super helpful and kindly agreed to create a dedicated Meetup event: https://www.meetup.com/Women-Who-Go-Paris/events/278894957/.
Registration is now open!

**Comment by jboursiquot** [comment]
@jub0bs Excellent! Once you've got the first round of announcement out, drop a note here and we'll amplify.

**Comment by jub0bs** [comment]
@jboursiquot Full house! We had to put some people on the waiting list. I'm currently "vetting" the participants (just to make sure they have the pre-requisites), but I'd say we already have enough people. Not sure whether advertising the event further on social media is warranted...

**Comment by jub0bs** [comment]
The session is over! Eight people registered but only three ended up attending the three days.

**Comment by jboursiquot** [comment]
Nice work @jub0bs! Yes, the registration to attendance ratio tends to be like that. Still, I'm sure the ones that attended all 3 days are the ones most likely to make the best out of what you've taught them. Thanks for doing this and hope you'll do it again in the future.
