### ISSUE TITLE
Intro to Programming with Go! - Baltimore

### ISSUE THREAD

**Issue by mastermndio** [gobridge/workshops#73]
Organizers: Aaron Brooks(MASTERMND) + Betamore

Venue or Online: Batamore

101 W Dickman St, Baltimore, MD 21230

Date: Saturday August 14, 2021

Curriculum: Custom Curriculum. Have to combine a few slides, then I will post here

### Logistic items
- [X] Has venue and it sits this many people: _75_ (if venue-based event, not applicable for Online events)
- [X] Has sponsor for food and drinks (for venue-based events)
- [X ] Has organizer(s)
- [X] Has teacher(s)
- [x] Has date
- [X] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started under a Meetup.com account managed by the Go Developer Network (GDN)--typically your local Go user group's online meetup.
- [x] Included in the event description if bikes are allowed inside or not (ask venue if venue-based event)
- [x] Included in the event description if child care is available or not (if venue-based event)

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all applicable tasks above are completed:exclamation:)

### A couple weeks before the venue-based event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer or when applicable)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [ ] Published and announced Meetup event with open registration
- [ ] First social media announcement's gone out
- [ ] Conducted organizer training (if applicable)
- [ ] Conducted teacher training (if applicable)
- [ ] Assignee added event date -1 week to calendar as reminder

### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [ ] Confirmed venue and date (if venue-based event)
- [ ] More rounds of announcements on social media. Mention how many spots left (if venue-based event)

**Comment by jboursiquot** [comment]
Hey @mastermndio! It's been a minute since we've chatted. Glad you're preparing a workshop. Let's chat soon: https://calendly.com/d/vryq-pxn6/let-s-chat

**Comment by mastermndio** [comment]
Hey @jboursiquot, are you the person who can help get the meetup page started? Here is the info. Let me know if I need to add/change anything

**Course**
This is an introductory event. The focus will be on learning programming fundamentals using Go.

This course aims to take those who are new to programming, and with the help of the Go programming language, help them get their first steps into this world.

**Workshop Description**
This is a BYOL event, please make sure to Bring Your Own Laptop with you for this workshop. We may have 2 or 3 to lend on the day of but they will be first come first serve. Don't worry if you haven't had Go installed on your laptop! The entire week leading up to the event will be a virtual Installfest! We will send out videos and documentation with step by step instructions on getting setup as well as access to a Discord you can use to get real time help if you run into trouble. We will also be on standby for 45 minutes before the event starts for anyone who wants to get there early for help. 

**FAQ:**
No previous knowledge is required
It's completely free
It's both for beginners and not-so beginners
While we encourage a the use of a modern  computer, any computer capable of installing a modern web browser will work as we will have web based options to participate. 

**Transportation and Parking**
Betamore is located at City Garage which has ample free parking directly in front of the facility. There are bike racks located inside of the building for those who need them. 

**Venue address:**
101 W Dickman St, Baltimore, MD 21230

**Time**
Doors open + Breakfast at 8:00am
Installfest 8:15-9:00am

9:00am-5:pm - Workshop
12:30-1:30 Lunch

**Food and Drinks**
We'll provide coffee/tea, donuts and bagels for breakfast.

Lunch will be provided as well but the options are still being determined. There will be vegetarian and vegan options available.

**Comment by jboursiquot** [comment]
@mastermndio yep, will get this on the Baltimore Go meetup ASAP.

**Comment by jboursiquot** [comment]
@mastermndio meetup event is up and ready for registrations: https://www.meetup.com/BaltimoreGolang/events/279890163/

**Comment by mastermndio** [comment]
Thanks for your help @jboursiquot This went really well. About 30 people.

**Comment by jboursiquot** [comment]
Glad to hear things went well @mastermndio.
