### ISSUE TITLE
GoLang Lokoja: Experience the Power of GO

### ISSUE THREAD

**Issue by stephendache** [gobridge/workshops#74]
Organizers: [Stephen Paul](https://linkedin.com/in/iamstepaul)

Venue or Online: Federal University Lokoja Auditorium (In-person),
Adankolo, Lokoja, Kogi State, Nigeria.

Date: December 15, 2023

Curriculum:

### Logistic items
- [x] Has venue and it sits this many people: ___ (if venue-based event, not applicable for Online events)
- [x] Has sponsor for food and drinks (for venue-based events)
- [x] Has organizer(s)
- [x] Has teacher(s)
- [x] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels) - Learn How To Code Google's Go (golang) Programming Language
- [x] Draft of event started under a Meetup.com account managed by the Go Developer Network (GDN)--typically your local Go user group's online meetup.
- [x] Included in the event description if bikes are allowed inside or not (ask venue if venue-based event)
- [x] Included in the event description if child care is available or not (if venue-based event)

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all applicable tasks above are completed:exclamation:)

### A couple weeks before the venue-based event
- [x] Order placed for catering, if applicable
- [x] Child care arranged for, if applicable

### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer or when applicable)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).

### After event is labeled as `scheduled`
- [x] Published and announced Meetup event with open registration
- [x] First social media announcement's gone out
- [x] Conducted organizer training (if applicable)
- [x] Conducted teacher training (if applicable)
- [x] Assignee added event date -1 week to calendar as reminder

### Presentations
- [x] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [x] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present

### Event date -1 week
- [x] Confirmed venue and date (if venue-based event)
- [x] More rounds of announcements on social media. Mention how many spots left (if venue-based event)

**Comment by jboursiquot** [comment]
Hey @iamstepaul, thanks for initiating a workshop. We'll need to have a quick call to clarify some next steps. Please pick a time that works for you here https://calendly.com/jboursiquot/30min.

**Comment by jboursiquot** [comment]
Ping @iamstepaul. Happy new year!
Is the event happening or did it happen? Sent you an email back on 12/15/23.
