### ISSUE TITLE
Denver, CO - Date: TBD 2016 - Course: Ultimate Go - Venue: Comcast

### ISSUE THREAD

**Issue by jheitz200** [gobridge/workshops#8]
Organizer: @jheitz200
Venue: Comcast
Date: TBD
Curriculum: Ultimate Go
### Logistic items
- [x] Has venue and it sits this many people: ___
- [ ] Has sponsor for food and drinks
- [x] Has organizer(s)
- [x] Has teacher(s): @extemporalgenome
- [ ] Has date
- [x] [Course selected](https://github.com/gobridge/workshops/blob/master/available_courses.md#course-descriptions-and-corresponding-levels)
- [ ] Draft of event started on [Bridge Troll](https://www.bridgetroll.org/events)
- [ ] Included in the event description if bikes are allowed inside or not (ask venue)
- [ ] Included in the event description if child care is available or not

(Issue ready :dart: to be labeled as `scheduled` :boom::v::tada::balloon::rocket: after all tasks above are completed:exclamation:)
### A couple weeks before the event
- [ ] Order placed for catering, if applicable
- [ ] Child care arranged for, if applicable
### First steps
- [x] Self-assigned the issue
- [x] Pinged the person who opened the issue
- [x] Google Hangout scheduled (if this is a first timer)

Continue taking the actions necessary to bring issue to a `scheduled` status according to our [issue workflow](https://github.com/gobridge/workshops/blob/master/issue_workflow.md).
### After event is labeled as `scheduled`
- [ ] Bridge Troll event made public; added event link to this thread
- [ ] Opened a meetup event to point to the Bridge Troll event (RSVP on meetup should be closed)
- [ ] Added a PR to add event to GoBridge's website (remove past events while at it)
- [ ] First social media announcement's gone out
- [x] Conducted organizer training
- [ ] Conducted teacher training
- [ ] Assignee added event date -1 week to calendar as reminder
### Presentations
- [ ] [Opening presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-welcome.slide) forked, edited, and ready to present
- [ ] [Closing presentation](https://github.com/gobridge/workshop-material/blob/master/organizer-closing.slide) forked, edited, and ready to present
### Event date -1 week
- [ ] Confirmed venue and date
- [ ] More rounds of announcements on social media. Mention how many spots left

**Comment by carlisia** [comment]
Hi @jheitz200! I would like to touch base with you about this workshop. Would you please email me at carlisia@golangbridge.org when you have a chance? Thank you.

**Comment by carlisia** [comment]
Had not meant to close this issue.

**Comment by carlisia** [comment]
@jheitz200 it was great chatting today.

So, after you have more info please check things off from the checklist here so we know you are not needing help with those things.

I'm working on finding you a teacher.

**Comment by carlisia** [comment]
@jheitz200, @extemporalgenome has graciously stepped up to teach the workshop! He will be teaching the course `Ultimate Go`, previously known in the GoBridge community as `Hardcore Go`.

I ask that you two please coordinate a date. 

We need (but should have zero trouble) to find TAs and volunteers to help. Once the date and other details are worked out and the Bridge Troll event created, we can send that event link so people can sign up to volunteer.

**Comment by carlisia** [comment]
c/c @levicook

**Comment by carlisia** [comment]
@jheitz200, FYI re: targeting college kids “in general”, from our mentors at RailsBridge/Bridge Foundry: https://gophers.slack.com/archives/gobridge-volunteers/p1449966594000018

**Comment by carlisia** [comment]
Hi @jheitz200, wanted to touch base with you on this. How is it going? Would it be helpful if I got more people to help out?

**Comment by carlisia** [comment]
Hi  @extemporalgenome and  @jheitz200, it would be great to run this workshop before GopherCon this year. We have a lot of friends there in Denver who could be of help. Please let us know if we can take the next step in helping make this happen (put the word out for a venue and/or sponsorship for food, etc) or if we should close this ticket until a more convenient time for you all. Thank you.

**Comment by carlisia** [comment]
Closing this issue due to organizer wanting to postpone. We are looking forward to having a workshop in Denver when the time is right!
