### ISSUE TITLE
SF : Nov 7th : Docker Fundamentals Workshop - Venue: Chain

### ISSUE THREAD

**Issue by jpetazzo** [gobridge/workshops#9]
Organizer: @jpetazzo
Venue: Chain (292 Ivy St, San Francisco, CA)
Date: November 7th
Curriculum: Docker

Details and RSVP: http://www.meetup.com/gobridge/events/225853880/
- [x] Confirm venue and date
- [x] Find curriculum, confirm license and what we can do with it
- [x] Sponsor for food breaks / drinks
- [x] Market it: write announcement
- [x] Market it: list of channels (GoSF, Docker Meetup, WomenWhoGo, https://www.bridgetroll.org/
  ... ?)
- [ ] Maybe enroll help, TAs

**Comment by Lyoness** [comment]
So awesome!  If this event is a success, we'd love for you to replicate it in NYC.

**Comment by kmolo** [comment]
> Market it: list of channels (GoSF, Docker Meetup, WomenWhoGo, Bridgetroll.org ... ?)

From my experience as an organizer for MobileBridge workshops ([GitHub](https://github.com/mobilebridge/organizing/issues))([Twitter](https://twitter.com/mobilebridgesf/media)), I highly recommend BridgeTroll ([website](https://www.bridgetroll.org/))([GitHub](https://github.com/railsbridge/bridge_troll))([Google Group for developers](https://groups.google.com/forum/#!forum/bridge-troll)) as an event management tool.  Other marketing spaces can be linked to it (i.e. Meetups.com events without open RSVPs that request in the Event Description that those interested RSVP on Bridgetroll).

Exciting to see GoBridge taking off.  Congratulations to all involved.

**Comment by ardan-bkennedy** [comment]
@kmolo We have looked into using it. It requires some changes and we have talked to Sarah Allen about it. Thanks for the suggestion.

**Comment by carlisia** [comment]
Announcement for this workshop: https://medium.com/@GolangBridge/gobridge-is-organizing-a-docker-workshop-7b8c1f5f6060#.bw81b7c12

**Comment by kmolo** [comment]
@jpetazzo 

First, really high-quality, dense/understandable workshop - really excellent.  Thank you.

Second, **is there a repo containing the slides that you used for this workshop?**

I have the link you provided with the PDF version of the slides that you used that day:

http://slides.dckr.info:88/DockerSlides.pdf

...but want to watch the repo, so I can follow along as training gets updated to reflect changes in Docker (e.g. all the container networking changes you thought might be coming up in the next 6-24 months).

---

For others following along with the excellent content that Docker & GoBridge are sharing, here are some additional Docker materials that @jpetazzo shared that day:
- orchestration workshop repo:  https://github.com/jpetazzo/orchestration-workshop
- security talk:  http://www.slideshare.net/jpetazzo/docker-linux-containers-lxc-and-security

**Comment by carlisia** [comment]
@kmolo :+1:

**Comment by jpetazzo** [comment]
Thanks for the feedback @kmolo, and sorry for the slow reply (after the workshop, I left for 3 weeks of non-stop travel for conferences). The source of the slides are in a private repo that also contains some material that I can't distribute... I'm working on splitting the slides however. If you send me an email I can send you an updated version that has more detailed support on docker networks and docker volumes!
